name: Manual workflow avec publication vers DockerHub

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
      
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Build with Gradle
      run: ./gradlew build -Dquarkus.package.type=native -Dquarkus.native.container-build=true publish

    - name: set up DockHub credentials
      uses: docker/login-action@v1
      with:
        username: legeniedesalpages
        password: 95b34d7b-2c41-4fb2-9280-2aa7982f2a5c

    - name: Push vers DockerHub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: .
          file: ./src/main/docker/Dockerfile.native
          platforms: linux/amd64
          push: true
          tags: mygreffe/stinger:latest
